### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by KnightDemons** [ObserverOfTime/poe-discord-rpc#2]
When I run it on windows, it seems to just open then instant close. Log into PoE and no RPC on Discord.

**Comment by ObserverOfTime** [comment]
Try running it from cmd/powershell/terminal.

**Comment by KnightDemons** [comment]
Running into this error.
![image](https://github.com/ObserverOfTime/poe-discord-rpc/assets/16524811/e032bffe-4350-468a-874b-f31210c3ad10)

**Comment by ObserverOfTime** [comment]
See harmonyland/discord_rpc#13

**Comment by ObserverOfTime** [comment]
I've switched to [discord_rpc_deno](https://github.com/xhayper/discord-rpc-deno) which should work.
